Update requirement comment for test_host_evacuate.py
xcp-ng/xcp-ng-tests pull request #113
Opened 2022-05-13 16:48 UTC by stormi

Minimum version is 8.3

Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>

2022-05-13 18:01 UTC, benjamreis requested changes
We should use the fixture enforcing a host > 8.3 then.

2022-05-13 18:06 UTC, stormi commented
I've done it already in a previous commit :)

2022-05-14 11:52 UTC, benjamreis commented
My bad, I missed it it seems! ^^'

2022-05-14 11:52 UTC, benjamreis approved these changes

2022-05-14 12:48 UTC, merged