Robustify teardown in storage tests + fix reboot issue in MooseFS tests
xcp-ng/xcp-ng-tests pull request #122
Opened 2022-05-25 14:04 UTC by stormi

Several commits, possibly better reviewed separately.

2022-05-25 14:45 UTC, benjamreis requested changes

2022-05-25 14:45 UTC, benjamreis commented on lib/pool.py
> +        If something fails, and execute rollback_func on each host on which the command was already executed.
```suggestion
        If something fails: execute rollback_func on each host on which the command was already executed.
```

2022-05-25 14:45 UTC, benjamreis commented on lib/pool.py
> +        If something fails, store the exception but still attempt the function on the next hosts.
```suggestion
        If something fails: store the exception but still attempt the function on the next hosts.
```

2022-05-25 14:45 UTC, benjamreis commented on lib/sr.py
> +                raise
The comment and code are contradictary

2022-05-25 14:45 UTC, benjamreis commented on lib/sr.py
> +            self.plug_pbd(pbd_uuid)
Would it make sense to make a `PBD` API?

2022-05-25 15:46 UTC, gduperrey approved these changes

2022-05-25 16:52 UTC, stormi commented
I added another commit that depends on the previous ones.

2022-05-25 17:02 UTC, benjamreis commented on lib/sr.py
> +                raise
My bad, you're right

2022-05-25 17:03 UTC, benjamreis approved these changes

2022-05-30 08:42 UTC, Wescoeur approved these changes

2022-05-30 10:01 UTC, merged