Trigger GC run and wait for it to complete before destroying a SR
xcp-ng/xcp-ng-tests pull request #80
Opened 2022-03-23 17:36 UTC by stormi

(this supersedes PR #79)

We encountered situations where the VDIs were not garbage collected
correctly when sr destroy is called, despite the fact that the driver's
delete method did trigger a forced GC run.

Based on upstream advice, we run sr scan to trigger a GC run and then
wait for the GC run to complete, before attempting the SR deletion.

See https://github.com/xapi-project/sm/issues/583

Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>

2022-03-23 17:40 UTC, Wescoeur approved these changes

2022-03-24 06:57 UTC, gduperrey approved these changes

2022-03-24 08:58 UTC, benjamreis approved these changes

2022-03-25 16:25 UTC, stormi commented
New way of trying to solve the SR destroy problem.

2022-03-25 18:37 UTC, benjamreis approved these changes

2022-03-28 07:46 UTC, gduperrey approved these changes

2022-03-28 13:39 UTC, Wescoeur requested changes

2022-03-28 13:39 UTC, Wescoeur commented on lib/host.py
> +            return result_as_list
I'm not sure if this is the right place for this code. This helper can be generic.
I think this new `split` param can be removed,  and this block could be moved in a new function executed after the `xe` call.

2022-03-28 13:39 UTC, Wescoeur commented on lib/sr.py
> +        return self.pool.master.xe('vdi-list', {'sr-uuid': self.uuid, 'managed': managed}, minimal=True, split=',')
So regarding my previous comment, you can have this code instead:
```python
    return non_empty_split(
        self.pool.master.xe('vdi-list', {'sr-uuid': self.uuid, 'managed': managed}, minimal=True)
    )
```

2022-03-28 15:43 UTC, Wescoeur approved these changes

2022-03-28 15:45 UTC, benjamreis requested changes

2022-03-28 15:45 UTC, benjamreis commented on lib/common.py
> +    return text.split(sep)
```suggestion
    return return [] if !len(text) else text.split(sep)
```

2022-03-28 15:54 UTC, benjamreis approved these changes

2022-03-28 15:56 UTC, merged